USE
techconnect_db;

INSERT INTO users (email, first_name, last_name, password, profile_picture, username)
VALUES ('zmolineux37@discovery.com', 'Zerk', 'Molineux', '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'zmolineux37'),
       ('rchurn38@omniture.com', 'Roderic', 'Churn', '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'rchurn38'),
       ('hskerman39@jugem.jp', 'Hastie', 'Skerman', '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'hskerman39'),
       ('kbarnwille3a@storify.com', 'Kathy', 'Barnwille',
        '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'kbarnwille3a'),
       ('lgarnall3b@eventbrite.com', 'Lexi', 'Garnall', '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'lgarnall3b'),
       ('mlamps3c@vk.com', 'Minette', 'Lamps', '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'mlamps3c'),
       ('nmatusevich3d@hibu.com', 'Ninnetta', 'Matusevich',
        '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'nmatusevich3d'),
       ('fredington3e@moonfruit.com', 'Fabiano', 'Redington',
        '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'fredington3e'),
       ('mflipek3f@photobucket.com', 'Maude', 'Flipek', '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'mflipek3f'),
       ('cglazer3g@wsj.com', 'Calla', 'Glazer', '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'cglazer3g'),
       ('mpomery3h@tripadvisor.com', 'Marilee', 'Pomery',
        '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'mpomery3h'),
       ('lrangeley3i@ft.com', 'Lance', 'Rangeley', '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'lrangeley3i'),
       ('fsmerdon3j@naver.com', 'Fernando', 'Smerdon', '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'fsmerdon3j'),
       ('benderlein3k@photobucket.com', 'Bonnie', 'Enderlein',
        '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'benderlein3k'),
       ('rpeevor3l@nbcnews.com', 'Rhea', 'Peevor', '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'rpeevor3l'),
       ('pkilcoyne3m@java.com', 'Philly', 'Kilcoyne', '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'pkilcoyne3m'),
       ('hbedell3n@oracle.com', 'Hannis', 'Bedell', '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'hbedell3n'),
       ('locannon3o@msu.edu', 'Lark', 'O''Cannon', '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'locannon3o'),
       ('tdellow3p@ox.ac.uk', 'Tailor', 'Dellow', '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'tdellow3p'),
       ('atebbut3q@flickr.com', 'Addia', 'Tebbut', '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'atebbut3q'),
       ('icrystal3r@google.com.br', 'Ibbie', 'Crystal', '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://cdn.filestackcontent.com//image.jpg', 'icrystal3r'),
       ('rizatson3s@nature.com', 'Roda', 'Izatson', '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'rizatson3s'),
       ('veakens3t@wordpress.org', 'Valaree', 'Eakens', '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'veakens3t'),
       ('binge3u@army.mil', 'Brena', 'Inge', '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'binge3u'),
       ('nmandell3v@meetup.com', 'Nonie', 'Mandell', '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'nmandell3v'),
       ('gduhig3w@cbslocal.com', 'Glynnis', 'Duhig', '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'gduhig3w'),
       ('mbrookfield3x@rambler.ru', 'Myrta', 'Brookfield',
        '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'mbrookfield3x'),
       ('cweald3y@woothemes.com', 'Cletus', 'Weald', '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'cweald3y'),
       ('rventon3z@cloudflare.com', 'Renata', 'Venton', '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'rventon3z'),
       ('jgiffen40@purevolume.com', 'Janela', 'Giffen', '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'jgiffen40'),
       ('gyearne41@cmu.edu', 'Gianni', 'Yearne', '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'gyearne41'),
       ('ldennison42@pagesperso-orange.fr', 'Leta', 'Dennison',
        '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'ldennison42'),
       ('dlarimer43@oaic.gov.au', 'Darrell', 'Larimer', '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'dlarimer43'),
       ('cneylon44@cdc.gov', 'Chico', 'Neylon', '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'cneylon44'),
       ('rdelooze45@amazon.co.uk', 'Roy', 'Delooze', '$2a$04$8spU8nkJPPPs/3NsOxsJFOMuAtAZ1150QzbbB9kXkIk6OXytLTzay',
        'https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/fd35c-no-user-image-icon-27.png?fit=500%2C500&ssl=1',
        'rdelooze45');


INSERT INTO interests (interest)
VALUES ('Web Development'),
       ('Data Science'),
       ('Computer programming'),
       ('Network Engineer'),
       ('Cyber Security'),
       ('Cloud Engineer'),
       ('UI/UX'),
       ('Systems Analyst'),
       ('Software Engineer'),
       ('Product Management');


INSERT INTO events (date_time, description, location, title, host_id, interest_id)
VALUES ('2023-07-02 14:00:00', 'Learn the latest web development techniques and tools.', 'New York City, NY',
        'Web Development Workshop', 10, 1),
       ('2023-07-05 09:30:00', 'Discover the world of data science and its applications.', 'San Francisco, CA',
        'Introduction to Data Science', 27, 2),
       ('2023-07-10 18:00:00', 'Explore the principles of user interface and user experience design.', 'Seattle, WA',
        'UI/UX Design Seminar', 4, 7),
       ('2023-07-12 13:15:00', 'Dive into the fundamentals of computer programming.', 'Boston, MA',
        'Introduction to Computer Programming', 15, 3),
       ('2023-07-15 10:00:00', 'Learn about the role of systems analysts in modern organizations.', 'Austin, TX',
        'Systems Analyst Conference', 19, 8),
       ('2023-07-18 16:30:00', 'Join us for a software engineering workshop and enhance your coding skills.',
        'Chicago, IL', 'Software Engineering Workshop', 22, 9),
       ('2023-07-20 11:45:00', 'Learn about cloud engineering and its applications in todays technology landscape.',
        'Denver, CO', 'Cloud Engineering Summit', 8, 6),
       ('2023-07-23 14:30:00', 'Discover the world of cybersecurity and learn how to protect digital assets.',
        'Washington, D.C.', 'Cybersecurity Seminar', 31, 5),
       ('2023-07-25 09:00:00', 'Explore the field of network engineering and its importance in modern networks.',
        'San Diego, CA', 'Introduction to Network Engineering', 3, 4),
       ('2023-08-02 16:00:00', 'Enhance your web development skills with advanced techniques and frameworks.',
        'New York City, NY', 'Advanced Web Development Seminar', 18, 1),
       ('2023-08-07 10:30:00', 'Unlock the power of data science in business decision-making.', 'San Francisco, CA',
        'Data Science for Business', 22, 2),
       ('2023-08-12 15:45:00', 'Learn how to create intuitive and visually appealing user interfaces.', 'Seattle, WA',
        'Mastering UI/UX Design', 31, 7),
       ('2023-08-16 11:00:00', 'Explore the world of algorithms and data structures in programming.', 'Boston, MA',
        'Algorithmic Problem Solving', 4, 2),
       ('2023-08-19 09:45:00', 'Discover the latest trends and innovations in systems analysis.', 'Austin, TX',
        'Systems Analysis Trends and Innovations', 19, 8),
       ('2023-08-22 14:15:00', 'Join us for a software engineering conference and network with industry experts.',
        'Chicago, IL', 'Software Engineering Conference', 7, 9),
       ('2023-08-25 10:30:00', 'Learn how to design and deploy scalable cloud solutions.', 'Denver, CO',
        'Scalable Cloud Solutions Workshop', 27, 6);

INSERT INTO discussions (content, created_at, title, user_id)
VALUES ('I am having trouble deploying my React app to AWS Amplify. Can anyone help?', '2023-07-01 10:00:00',
        'Trouble with React app deployment to AWS Amplify', 22),
       ('What are some best practices for optimizing SQL queries in large databases?', '2023-07-02 14:30:00',
        'Optimizing SQL queries in large databases', 18),
       ('I am working on a machine learning project and need help with feature selection techniques.',
        '2023-07-03 09:15:00', 'Feature selection techniques for machine learning project', 29),
       ('How can I improve the performance of my website? Looking for tips and suggestions.', '2023-07-04 16:45:00',
        'Tips for improving website performance', 12),
       ('I am exploring different cloud providers for my application. Which one would you recommend?',
        '2023-07-05 11:30:00', 'Choosing a cloud provider for application hosting', 7),
       ('What are some good resources to learn Python for beginners?', '2023-07-06 13:00:00',
        'Learning Python as a beginner', 35),
       ('How can I secure my web application against common security vulnerabilities?', '2023-07-07 15:30:00',
        'Securing web applications against common vulnerabilities', 24),
       ('Looking for recommendations on front-end frameworks for building responsive websites.', '2023-07-08 12:45:00',
        'Recommendations for front-end frameworks for responsive web design', 9),
       ('What are some essential skills and qualifications for a data scientist?', '2023-07-09 17:15:00',
        'Essential skills and qualifications for a data scientist', 31),
       ('Seeking advice on choosing the right programming language for a machine learning project.',
        '2023-07-10 10:30:00', 'Choosing the right programming language for a machine learning project', 4),
       ('How can I improve the performance of my database queries in a high-traffic application?',
        '2023-07-11 14:15:00', 'Optimizing database query performance in high-traffic applications', 17);


INSERT INTO comments (title, content, created_at, discussion_id, user_id)
VALUES ('Solution for React app deployment issue',
        'I had a similar issue before, and I solved it by checking my build configuration. Make sure you have the correct settings for AWS Amplify.',
        '2023-07-01 10:30:00', 1, 15),
       ('Assistance for React app deployment',
        'I can assist you with your React app deployment. Have you encountered any specific error messages?',
        '2023-07-01 11:15:00', 1, 27),
       ('Approach for optimizing SQL queries',
        'One approach for optimizing SQL queries in large databases is to create appropriate indexes for frequently queried columns.',
        '2023-07-02 15:00:00', 2, 12),
       ('Recommendation for improving SQL query performance',
        'I recommend using query execution plans to identify potential performance bottlenecks in your SQL queries.',
        '2023-07-02 15:30:00', 2, 8),
       ('Feature selection techniques for machine learning projects',
        'For feature selection in machine learning projects, you can try techniques like forward selection or backward elimination to identify the most relevant features.',
        '2023-07-03 10:00:00', 3, 21),
       ('Evaluation of feature selection techniques',
        'I suggest using cross-validation methods to evaluate the performance of your feature selection techniques.',
        '2023-07-03 10:45:00', 3, 4),
       ('Techniques to improve website performance',
        'Caching static assets, enabling compression, and optimizing images are some techniques to improve website performance.',
        '2023-07-04 17:00:00', 4, 9),
       ('Using a CDN for website performance',
        'Using a content delivery network (CDN) can also significantly enhance your websites performance.',
        '2023-07-04 17:30:00', 4, 33),
       ('Choosing a cloud provider',
        'AWS, Google Cloud, and Microsoft Azure are popular cloud providers. Consider factors like pricing, scalability, and available services when choosing one.',
        '2023-07-05 12:00:00', 5, 18),
       ('Try out free tiers of cloud providers',
        'I recommend trying out the free tiers of different cloud providers to see which one fits your applications requirements best.',
        '2023-07-05 12:45:00', 5, 31),
       ('Resources for learning Python',
        'For beginners learning Python, online tutorials, interactive coding platforms, and books like "Python Crash Course" are great resources.',
        '2023-07-06 13:30:00', 6, 23),
       ('Recommended Python resource for beginners',
        'I found "Automate the Boring Stuff with Python" to be an excellent resource for beginners. Give it a try!',
        '2023-07-06 14:15:00', 6, 14),
       ('Security practices for web applications',
        'To secure your web application, use secure coding practices, input validation, and encryption for sensitive data.',
        '2023-07-07 16:00:00', 7, 2),
       ('Regularly update dependencies for web application security',
        'Regularly update your web applications dependencies and frameworks to patch security vulnerabilities.',
        '2023-07-07 16:45:00', 7, 26);

INSERT INTO review(event_id, user_id, rating, title, description)
VALUES (1, 10, 4, 'Informative and helpful workshop',
        'The Web Development Workshop was very informative and provided helpful insights into the latest web development techniques.'),
       (2, 27, 5, 'Excellent introduction to data science',
        'The Introduction to Data Science event exceeded my expectations. The speaker was knowledgeable, and the content was well-structured.'),
       (3, 4, 3, 'Could use more practical examples',
        'While the UI/UX Design Seminar covered the principles well, I would have liked to see more practical examples and case studies.'),
       (4, 15, 4, 'Valuable introduction to computer programming',
        'The Introduction to Computer Programming session provided a solid foundation for beginners. The instructor explained concepts clearly.'),
       (5, 18, 5, 'Insightful conference on systems analysis',
        'The Systems Analyst Conference was packed with valuable insights and real-world examples. I highly recommend it to professionals in the field.'),
       (6, 23, 4, 'Great workshop for learning Python',
        'The Python workshop was well-structured, and the hands-on exercises helped reinforce my understanding of the language.'),
       (7, 2, 2, 'Lacked in-depth coverage of security topics',
        'The Cybersecurity Seminar didn''t cover the topic in enough depth. I expected more comprehensive discussions on common vulnerabilities and mitigation strategies.'),
       (8, 29, 5, 'Excellent recommendations for front-end frameworks',
        'The Recommendations for Front-end Frameworks event provided valuable insights into the strengths and weaknesses of different frameworks.'),
       (9, 11, 4, 'Insightful session on essential data science skills',
        'The Essential Skills and Qualifications for a Data Scientist session covered a wide range of skills necessary for a successful career in data science.'),
       (10, 6, 3, 'Lacked comparison between programming languages',
        'The session on choosing the right programming language could have provided a better comparison between different languages.'),
       (11, 17, 5, 'Optimization techniques for high-traffic applications',
        'The session on optimizing database query performance in high-traffic applications offered practical strategies that I could implement in my project.');
